# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.box_check_update = true
  config.vm.provider "virtualbox" do |vb|
    vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
  end

  config.vm.provision "shell", path: "provision.sh"

  config.vm.define "master-deb-k0s" do |master|
    master.vm.hostname = "master-deb-k0s"
    master.vm.network "private_network", ip: "10.10.10.20"
#    master.vm.network "public_network", bridge: "Killer Wireless-n/a/ac 1535 Wireless Network Adapter"
    master.vm.network "public_network", bridge: "wlp8s0"
#    master.vm.provision "shell", path: "master.sh"
    master.vm.provider "virtualbox" do |v|
      v.name = "master_deb_k0s"
      v.memory = 2048
      v.cpus = 2
    end
  end

  $instance=2
  (1..$instance).each do |i|
         config.vm.define "node-deb-k0s#{i}" do |node|
           node.vm.hostname =  "node-deb-k0s#{i}"
           node.vm.network "private_network", ip: "10.10.10.#{i+20}"
           node.vm.provider "virtualbox" do |v|
            v.name = "node_deb_k0s#{i}"
            v.memory = 1024
            v.cpus = 1
           end
#           node.vm.provision "shell", path: "worker.sh"
         end
  end
end
